spring.application.name=expenseTracker
spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracker
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=95uwO7doSJcGBTviCq9QzSTwhdvQq7W3glMM8wWefiV
jwt.expiration=86400000

logging.file.name=logs/expense-tracker.log

logging.level.root=INFO
logging.level.com.example.expenseTracker=DEBUG

